"""Experiments from configs/queue.yaml become one Kaggle GPU kernel, one lane per GPU.

The kernel script is generated: it fetches this public repo at the exact commit, pins the
package versions the CPU smoke test ran with, prepares data once per lane (so lanes never race on
the frame cache), then runs every lane in parallel with its own CUDA_VISIBLE_DEVICES. Each lane
writes /kaggle/working/<run_id>/ (see reva.job). The last log line is "EXIT <worst code>".

Each job gets its own kernel slug (reva-<first run id>), so a run's private outputs, including the
submission zip, stay downloadable later by that slug.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from reva import config as C
from reva.kaggle import kernel_metadata

KAGGLE_PATHS = {"data.root": "/kaggle/tmp/reva", "data.video_root": "/kaggle/tmp/reva",
                "frames.cache": "/kaggle/tmp/frames"}


def load_queue(path: str | Path) -> list[dict]:
    items = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or []
    for it in items:
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]{1,30}", str(it.get("name", ""))):
            raise ValueError(f"queue name must be 2-31 chars of a-z, 0-9, '-': {it.get('name')!r}")
        it.setdefault("set", {})
    return items


def run_config(base: dict, item: dict) -> dict:
    """Defaults plus the item's overrides, with a run id that changes whenever the config does."""
    cfg = C.override(base, {k: v for k, v in item["set"].items()})
    cfg.pop("run_id", None)
    cfg["run_id"] = f"{item['name']}-{C.experiment_fingerprint(cfg)[:8]}"
    cfg["why"] = item.get("why", "")
    return cfg


def pending(base: dict, queue: list[dict], done: set[str], failed: dict[str, int], max_fail: int = 2) -> list[dict]:
    """Queue order, skipping runs already finished or failed max_fail times. An entry's `done_as`
    maps its current run id to an older id of the same experiment (made before the run id left out
    orchestration). The alias stops matching as soon as the entry's experiment changes."""
    out = []
    for item in queue:
        cfg = run_config(base, item)
        if (item.get("done_as") or {}).get(cfg["run_id"]) in done:
            continue
        if cfg["run_id"] not in done and failed.get(cfg["run_id"], 0) < max_fail:
            out.append(cfg)
    return out


def kernel_script(lanes: list[dict], sha: str, repo: str, pip: list[str]) -> str:
    lanes = [C.override(c, KAGGLE_PATHS) for c in lanes]
    return f'''# Generated by reva.remote for commit {sha}. Do not edit by hand.
import json, os, subprocess, sys, time
SHA = {sha!r}
REPO = {repo!r}
PIP = {pip!r}
LANES = json.loads({json.dumps(json.dumps(lanes))})
T, W = "/kaggle/tmp", "/kaggle/working"

def sh(cmd):
    print("+", cmd, flush=True)
    subprocess.run(cmd, shell=True, check=True)

os.makedirs(T, exist_ok=True)
sh(f"rm -rf {{T}}/repo && git init -q {{T}}/repo && cd {{T}}/repo && git fetch -q --depth 1 {{REPO}} {{SHA}} && git checkout -q FETCH_HEAD")
sh("pip install -q " + " ".join(f'"{{p}}"' for p in PIP))
# the image ships torchao 0.10.0 (8 Oct 2026); peft 0.21.2 refuses to add LoRA next to a torchao
# older than 0.16, and nothing here uses it
sh("pip uninstall -y -q torchao || true")
sh(f"pip install -q --no-deps -e {{T}}/repo")
paths = []
for cfg in LANES:
    p = f"{{T}}/{{cfg['run_id']}}.json"
    open(p, "w").write(json.dumps(cfg))
    paths.append(p)
for p in paths:  # one at a time: downloads and frame caches are shared between lanes
    sh(f"cd {{T}}/repo && python -m reva.job --prepare-only --config {{p}} --out {{W}}")
procs = []
for gpu, (cfg, p) in enumerate(zip(LANES, paths)):
    out = f"{{W}}/{{cfg['run_id']}}"
    os.makedirs(out, exist_ok=True)
    env = {{**os.environ, "CUDA_VISIBLE_DEVICES": str(gpu), "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True"}}
    log = open(f"{{out}}/log.txt", "w")
    procs.append((cfg["run_id"], log, subprocess.Popen([sys.executable, "-m", "reva.job", "--config", p, "--out", out],
                                                      cwd=f"{{T}}/repo", env=env, stdout=log, stderr=subprocess.STDOUT)))
codes = []
for run_id, log, proc in procs:
    codes.append(proc.wait())
    log.close()
    print(f"== {{run_id}} exit {{codes[-1]}}", flush=True)
    print("".join(open(f"{{W}}/{{run_id}}/log.txt").readlines()[-40:]), flush=True)
print("EXIT", max(codes), flush=True)
'''


def build(base: dict, lanes: list[dict], sha: str, out_dir: str | Path, user: str, hours: float | None = None,
          stamp: str = "") -> str:
    """Write kernel-metadata.json and job.py into out_dir. Returns the kernel slug.

    `stamp` (the push time) makes the slug unique. A push to an existing slug makes a new version,
    and Kaggle serves only the latest version's output, so reusing a slug loses every earlier
    run's adapter and probabilities (8 Oct 2026: a retry would have overwritten our best run).

    `hours` shortens the session to what the account has left this week. Each lane keeps the usual
    margin for setup, and training sizes itself to the shorter lane (reva.job.train_deadline). The
    run ids do not change: the same experiment, given less time.
    """
    if not lanes:
        raise ValueError("no lanes to run")
    if hours is not None:
        setup = C.get(base, "remote.max_hours") - C.get(base, "job.max_hours")
        lanes = [C.override(c, {"job.max_hours": min(C.get(c, "job.max_hours"), round(hours - setup, 2))})
                 for c in lanes]
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    tail = f"-{stamp}" if stamp else ""
    # Kaggle titles take at most 50 characters; trim the run id, never the stamp
    slug = f"{user}/" + (f"reva-{lanes[0]['run_id']}"[:50 - len(tail)].rstrip("-") + tail).lower()
    (out_dir / "job.py").write_text(kernel_script(lanes, sha, C.get(base, "remote.repo"), C.get(base, "remote.pip")))
    meta = kernel_metadata(slug, "job.py", gpu=True, accelerator=C.get(base, "remote.accelerator"))
    (out_dir / "kernel-metadata.json").write_text(json.dumps(meta, indent=1))
    return slug
